### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by ulfryk** [tifosiblack/typescript-helpers#1]
Great job @tifosiblack !

It would be great if this lib was added to bower registry (needs bower.json and registering).

If you like I can prepare PR for that.

**Comment by tifosiblack** [comment]
Thanks, I started this repository in order to better minifying transpiled Typescript code.

I published it on Bower right now.

**Comment by ulfryk** [comment]
THX - I started using your little library on production :)

**Comment by ulfryk** [comment]
Ohh, one more issue context of bower - can you add tag "v1.0.0" (release) to your master branch so bower can recognize version ?

**Comment by tifosiblack** [comment]
I used bower version, but got a patch bump... It will be 1.0.1.

**Comment by ulfryk** [comment]
bower.json version is useless without a tag :(

**Comment by ulfryk** [comment]
see:

```
$ bower info typescript-helpers
bower not-cached    git://github.com/tifosiblack/typescript-helpers.git#*
bower resolve       git://github.com/tifosiblack/typescript-helpers.git#*
bower checkout      typescript-helpers#master
bower resolved      git://github.com/tifosiblack/typescript-helpers.git#bbb931e234

{
  name: 'typescript-helpers',
  description: 'Typescript helpers for compiling typescript while specifying --noEmitHelpers',
  main: 'helpers.js',
  authors: [
    'Clément Fossati <fossati.clement@gmail.com>'
  ],
  license: 'MIT',
  homepage: 'https://github.com/tifosiblack/typescript-helpers',
  moduleType: [],
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ]
}

No versions available.
```

**Comment by tifosiblack** [comment]
I see, I thought it was a git tag, and bower version command added one.

**Comment by ulfryk** [comment]
@tifosiblack - thanks a lot - working fine now :)
