### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by ulfryk** [tifosiblack/typescript-helpers#2]
It would be great if lib was tested for compatibility with current TypeScript.

**Comment by tifosiblack** [comment]
I extracted them from Typescript code directly. It was on version 1.7.3 I think. It's probably pretty stable code.

**Comment by ulfryk** [comment]
I think versions will change, helpers may evolve, etc, etc ;)

**Comment by RReverser** [comment]
And one problem is here already: `__awaiter` implementation differs from one generated by TypeScript without the flag:

```javascript
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator.throw(value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments)).next());
    });
};
```

More specifically, TS generates code with `void 0` as third argument, and then auto-generated `__awaiter` works while the one from this repo fails.

**Comment by tifosiblack** [comment]
Please look at https://github.com/Microsoft/tslib
